version: '3.9'
services:
  qdrant:
    image: qdrant/qdrant:v1.1.0
    volumes:
      - ./qdrant_data:/data
  proxy:
    image: nginx:stable-alpine
    ports:
      - 6333:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - qdrant
